### ISSUE TITLE
(libuv) Failed to create kqueue (24)

### ISSUE THREAD

**Issue by rentiansheng** [rentiansheng/devSync#5]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EBADF
    at errnoException (net.js:905:11)
    at WriteStream.Socket._write (net.js:646:26)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.log (console.js:54:16)
    at listenToChange (/Users/baidu/git/devSync/client/watch.js:45:15)
    at watchDir (/Users/baidu/git/devSync/client/watch.js:54:5)
    at /Users/baidu/git/devSync/client/watch.js:67:17

**Comment by rentiansheng** [comment]
fs 获取目下下内容是，如果目录使用的文字编码出现问题。在使用fs.readdir使用utf8编码就行了。
