### ISSUE TITLE
 throw errnoException(process._errno, 'watch');

### ISSUE THREAD

**Issue by rentiansheng** [rentiansheng/devSync#6]
fs.js:1063
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at listenToChange (/Users/baidu/git/devSync/client/watch.js:43:8)
    at watchDir (/Users/baidu/git/devSync/client/watch.js:49:5)
    at /Users/baidu/git/devSync/client/watch.js:60:17
    at Object.oncomplete (fs.js:108:15)

**Comment by rentiansheng** [comment]
watch dir to many. please exec  ulimit -n 4000;
